stages:
  - dependency

whitesource:
  only:
    refs:
     - master
     - develop
  tags:
    - whitesource_ci
  stage: dependency
  script:
    - java -jar /usr/bin/wss-unified-agent.jar -apiKey $WSS_API_KEY -projectToken $WSS_CNI_DNS_TOKEN -userKey $WSS_USER_KEY  -c ./ci/wss-dns-cni.conf -d ./ -scanComment $CI_COMMIT_SHORT_SHA